book_of_recipes/book_of_recipes/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('catalog.urls', namespace='recipe_catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')) ,
]


if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
        ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book_of_recipes/carts/urls.py
from django.urls import path
from carts import views


app_name = "carts"

urlpatterns = [
    path("favorite-recipes/", views.ShowFavoriteRecipes.as_view(), name="favorite_recipes"),
    path("cart-add/<int:recipe_id>/", views.cart_add, name="cart_add"),
    path("users-recipes/", views.UsersRecipesPage.as_view(), name="users_recipes"),
    path(
        "create-subscription/<int:creator_id>/",
        views.create_subscription,
        name="create_subscription",
    ),
    path(
        "favorite-authors/<int:user_id>/",
        views.favorite_authors,
        name="favorite_authors",
    ),
    path(
        "subscribers/<int:user_id>/", views.subscribers_of_the_user, name="subscribers"
    ),
]

book_of_recipes/catalog/urls.py
from django.urls import  path
from catalog import views

app_name = "catalog"

urlpatterns = [
    path('search/',views.show_catalog, name='search' ),
    path("category/<slug:category_slug>/", views.show_catalog, name="catalog"),
    path("recipe/<slug:recipe_slug>/", views.ShowRecipe.as_view(), name="recipe"),
    path("user-add-recipe/", views.AddPage.as_view(), name="user_add_recipe"),
    path(
        "change/<slug:slug>/", views.UpdatePage.as_view(), name="change_the_recipe"
    ),
    path("remove/<slug:slug>/", views.DeletePage.as_view(), name="remove"),
    ]

book_of_recipes/main/urls.py
from django.urls import path
from main import views


app_name = "main"

urlpatterns = [
  path('', views.MainPage.as_view(), name='index'),
  path('about/', views.AboutPage.as_view(), name='about'),
  
 
]

book_of_recipes/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView
from django.urls import path
from users import views


app_name = "users"

urlpatterns = [
    path("login/", views.LoginUser.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "password-change/", views.UserPasswordChange.as_view(), name="password_change"
    ),
    path(
        "password-change/done/",
        PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
        name="password_change_done",
    ),
    path("registration/", views.RegistrationUser.as_view(), name="registration"),
    path("user-settings/", views.user_settings, name="user_settings"),
    path("profile/", views.ShowProfile.as_view(), name="profile_user"),
    
    path("creators/", views.ShowAuthors.as_view(), name="creators"),
    path("creator/<int:user_id>/", views.ShowAuthorProfile.as_view(), name="creator"),
]

book_of_recipes/templates/base.html
{% load static %}
{% load recipe_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'deps/css/my_css.css' %}">

    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'deps/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'deps/favicon/favicon-16x16.png' %}">

    <title>{{ title }}</title>
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href='{% url "main:index" %}' index.html">COOKING at HOME</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Информация
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="{% url 'main:about' %}">О нас</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link  text-white" href="{% url 'user:creators' %}">Авторы</a>
                    </li>
                        {% if not user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="{% url 'user:login' %}">Войти</a>
                        </li> 
                        {% else %}
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Мой профиль
                            </a>
                        
                            <ul class="dropdown-menu">
                                
                                <li><a class="dropdown-item  text-white" href="{% url 'user:profile_user' %}">Личный кабинет</a>
                                </li>
                                {% if user.is_admin or user.is_staff %}
                                <li><a class="dropdown-item  text-white" href="{% url 'admin:index' %}">Админ панель</a></li>
                                {% endif %}
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item  text-white" href="{% url 'user:logout' %}">Выйти</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Моя книга рецептов
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="{% url 'cart:users_recipes' %}">Посмотреть мои рецепты</a>
                                </li>
                                <li><a class="dropdown-item  text-white" href="{% url 'recipe_catalog:user_add_recipe' %}">Добавить рецепт</a>
                                </li>
                            </ul>
                    </li>
                    </ul>
                    {% endif %}  
                
                </div>
            </div>
        </nav>
    </header>
    <section>
        <div class="container">
            <!-- Каталог с фиксированным расположением на странице -->
            <div class="row mt-1 position-fixed z-3">
                <!-- Каталог -->
               {% block button %}{% endblock %}
        </div>
        <!-- Контент -->
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2">
                 <!-- Пустой блок -->
                </div>
                <div class = "col-lg-10 ">
                     <!-- Контент на странице -->
         
                   {% block content %}{% endblock %}
                </div>
    </section>
    {% block footer %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>