book_of_recipes/book_of_recipes/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('catalog.urls', namespace='recipe_catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')) ,
]


if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
        ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book_of_recipes/catalog/urls.py
from django.urls import  path
from catalog import views

app_name = "catalog"

urlpatterns = [
    path('search/',views.show_catalog, name='search' ),
    path("category/<slug:category_slug>/", views.show_catalog, name="catalog"),
    path("recipe/<slug:recipe_slug>/", views.ShowRecipe.as_view(), name="recipe"),
    path("user-add-recipe/", views.AddPage.as_view(), name="user_add_recipe"),
    path(
        "change/<slug:slug>/", views.UpdatePage.as_view(), name="change_the_recipe"
    ),
    path("remove/<slug:slug>/", views.DeletePage.as_view(), name="remove"),
    ]

book_of_recipes/main/urls.py
from django.urls import path
from main import views


app_name = "main"

urlpatterns = [
  path('', views.MainPage.as_view(), name='index'),
  path('about/', views.AboutPage.as_view(), name='about'),
  
 
]

book_of_recipes/main/models.py
from django.db import models

# Create your models here.

book_of_recipes/main/views.py
from django.views.generic import ListView, TemplateView
from catalog.models import Recipe


class MainPage(ListView):
    template_name = "main/index.html"
    context_object_name = "recipes"
    title_page = "COOKING at HOME - Главная"
    paginate_by = 5

    def get_queryset(self):
        return Recipe.objects.filter(cooking_time__lt=35)


class AboutPage(TemplateView):
    template_name = "main/about.html"
    title_page = "COOKING at HOME - О нас"

book_of_recipes/main/templates/main/about.html
{% extends 'base.html' %}
{% load static %}
        
</head>

<body> 
    {% block content %}
    <div class= "bg-white  mt-3 p-4 mb-4 rounded custom-shadow row ">
    <h1 class="pt-3 "><strong>Правильное питание как философия жизни!</strong></h1>
    <h2>"Питаться - это необходимость, но разумно питаться - это <br>
       искусство",— Франсуа VI де Ларошфуко.</h2><br>
     <p class='text-bg-light'>
        Правильное питание (ПП) поможет вам значительно улучшить качество жизни и чувствовать себя прекрасно, и хотя вести здоровый образ жизни может показаться трудным и скучным, на самом деле это не так. Приготовить полезную еду достаточно просто. Откажитесь от большого количества сахара, белой рафинированной муки и жира в повседневных рецептах. Жарку в большом количестве масла замените на запекание в духовке в собственном соку. Мы докажем, что полезная еда может быть еще и вкусной. Здесь собраны простые ПП рецепты на каждый день, на наш взгляд это идеальное решение для людей, которые ведут здоровый образ жизни.   Присоединяйтесь к нам и делитесь своими рецептами.<p>
 
    <div class ='text-center'>
        <h3 class = 'text-bg-warning'>Питайтесь правильно!Готовьте с удовольствием! Приятного аппетита! </h3></div>
    </div>
    {% endblock %}
    

book_of_recipes/main/templates/main/index.html
 {% extends 'base.html' %} 
{% load static %}
{% load recipe_tags %}
{% block button %}
<div class="dropdown mb-2 mt-1 pt-2">
    <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
        aria-expanded="false">
        Рецепты
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="white" class="bi bi-grid-fill" viewBox="0 0 16 16">
            <path d="M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zm8 0A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm-8 8A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm8 0A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3z"/>
          </svg>
   
    </button>
    <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
    {%  tag_category as categories %}
        {% for category  in categories %}
        <li><a class="dropdown-item text-white" href='{% url "recipe_catalog:catalog" category.slug %}'>{{ category.name }}</a></li>
        {% endfor %}
    </ul>
</div>
</div>
{% endblock %}
    {% block content %}
    <h1 class="mt-5 pt-3"><strong> COOKING at HOME - книга полезных рецептов</strong></h1>
   {% for card in recipes %}
  <!-- Карта товара -->
  <div class="col-lg-4 col-md-6 p-4 ">
      <div class="card border-primary rounded custom-shadow">
        {% if card.image %}
         <img src="{{ card.image.url }}" class="card-img-top" alt="{{ card.name_recipe }}">
         {% else %}
         <img src="{% static 'deps/images/Not found image.png' %}" class="card-img-top" alt="{{ card.name_recipe }}">
        {% endif %}
          <div class="card-body">
              <a href=" {{ card.get_absolute_url }}">
                  <p class="card-title">{{ card.name_recipe }}</p>
              </a>
              <p class="card-text text-truncate"><strong>Время приготовления:</strong> {{ card.cooking_time }} мин</p>
              <p class="card-text text-truncate"><strong>Категория:</strong> {{ card.category }}</p>
              <p class="product_id">{{card.author }}</p>
              <div class="d-flex justify-content-between">
        
              </div>
          </div>
      </div>
  </div>
  {% endfor %}
    {% endblock %}
    
    {% block footer %}
    <footer class="py-2 bg-primary sticky-bottom">
        <div class="container">
            <p class="m-0 text-center text-white"> COOKING at HOME; The site was created in Python using the framework Django</p>
        </div>
    </footer>    
    {% endblock%}