book_of_recipes/book_of_recipes/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('catalog.urls', namespace='recipe_catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')) ,
]


if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
        ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book_of_recipes/carts/urls.py
from django.urls import path
from carts import views


app_name = "carts"

urlpatterns = [
    path("favorite-recipes/", views.ShowFavoriteRecipes.as_view(), name="favorite_recipes"),
    path("cart-add/<int:recipe_id>/", views.cart_add, name="cart_add"),
    path("users-recipes/", views.UsersRecipesPage.as_view(), name="users_recipes"),
    path(
        "create-subscription/<int:creator_id>/",
        views.create_subscription,
        name="create_subscription",
    ),
    path(
        "favorite-authors/<int:user_id>/",
        views.favorite_authors,
        name="favorite_authors",
    ),
    path(
        "subscribers/<int:user_id>/", views.subscribers_of_the_user, name="subscribers"
    ),
]

book_of_recipes/catalog/urls.py
from django.urls import  path
from catalog import views

app_name = "catalog"

urlpatterns = [
    path('search/',views.show_catalog, name='search' ),
    path("category/<slug:category_slug>/", views.show_catalog, name="catalog"),
    path("recipe/<slug:recipe_slug>/", views.ShowRecipe.as_view(), name="recipe"),
    path("user-add-recipe/", views.AddPage.as_view(), name="user_add_recipe"),
    path(
        "change/<slug:slug>/", views.UpdatePage.as_view(), name="change_the_recipe"
    ),
    path("remove/<slug:slug>/", views.DeletePage.as_view(), name="remove"),
    ]

book_of_recipes/main/urls.py
from django.urls import path
from main import views


app_name = "main"

urlpatterns = [
  path('', views.MainPage.as_view(), name='index'),
  path('about/', views.AboutPage.as_view(), name='about'),
  
 
]

book_of_recipes/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView
from django.urls import path
from users import views


app_name = "users"

urlpatterns = [
    path("login/", views.LoginUser.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "password-change/", views.UserPasswordChange.as_view(), name="password_change"
    ),
    path(
        "password-change/done/",
        PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
        name="password_change_done",
    ),
    path("registration/", views.RegistrationUser.as_view(), name="registration"),
    path("user-settings/", views.user_settings, name="user_settings"),
    path("profile/", views.ShowProfile.as_view(), name="profile_user"),
    
    path("creators/", views.ShowAuthors.as_view(), name="creators"),
    path("creator/<int:user_id>/", views.ShowAuthorProfile.as_view(), name="creator"),
]

book_of_recipes/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(
        upload_to="users_images", blank=True, null=True, verbose_name="аватар"
    )

    class Meta:
        db_table = "user"
        verbose_name = "Пользователя"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

book_of_recipes/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import (
    AuthenticationForm,
    UserCreationForm,
    UserChangeForm,
    PasswordChangeForm
)



class UserLoginForm(AuthenticationForm):

    class Meta:
        model = get_user_model()
        fields = ["username", "password"]


class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        )

    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.EmailField()
    password1 = forms.CharField()
    password2 = forms.CharField()

    def clean_email(self):
        email = self.cleaned_data["email"]
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Пользователь с таким email уже существует")
        return email


class UserProfileForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            "image",
            "first_name",
            "last_name",
            "username",
            "email",
        )

    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()


class UserPasswordChageForm(PasswordChangeForm):
     old_password = forms.CharField()
     new_password1 = forms.CharField()
     new_password2 = forms.CharField()

book_of_recipes/users/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.urls import reverse, reverse_lazy
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from django.db.models import F

from .models import User
from catalog.models import Recipe
from users.forms import (
    UserLoginForm,
    UserRegistrationForm,
    UserProfileForm,
    UserPasswordChageForm,
)
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin


class LoginUser(LoginView):
    form_class = UserLoginForm
    template_name = "users/login.html"
    extra_context = {"title": "Авторизация"}

    def get_success_url(self) -> str:
        return reverse_lazy("main:index")


class RegistrationUser(CreateView):
    form_class = UserRegistrationForm
    template_name = "users/registration.html"
    success_url = reverse_lazy("user:login")


# def registration(request):
#     if request.method == "POST":
#         form = UserRegistrationForm(data=request.POST)
#         if form.is_valid():
#             form.save()
#             user = form.instance
#             auth.login(request, user)
#             messages.success(request, f"{user.username}, вы успешно зарегестрированы!")
#             return HttpResponseRedirect(reverse("main:index"))
#     else:
#         form = UserRegistrationForm()
#     context = {"title": "Регистрация", "form": form}
#     return render(request, "users/registration.html", context)


@login_required
def user_settings(request):
    if request.method == "POST":
        form = UserProfileForm(
            data=request.POST, instance=request.user, files=request.FILES
        )
        if form.is_valid():
            form.save()
            user = form.instance
            auth.login(request, user)

            return HttpResponseRedirect(reverse("user:user_settings"))
    else:
        form = UserProfileForm(instance=request.user)

    context = {"title": "Кабинет", "form": form}
    return render(request, "users/user_settings.html", context)




class ShowProfile(LoginRequiredMixin, ListView):
    model = auth.get_user_model()

    template_name = "users/user_profile.html"
    context_object_name = "recipes"

    def get_queryset(self):
        return Recipe.objects.filter(author=self.request.user)




class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChageForm
    success_url = reverse_lazy("user:password_change_done")
    template_name = "users/password_change_form.html"




class ShowAuthors(ListView):
    model = auth.get_user_model()
    template_name = "users/creators.html"
    context_object_name = "creators"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        creators = [
            creator for creator in context["object_list"] if creator.authors.exists()
        ]
        context["creators"] = creators
        return context




class ShowAuthorProfile(ListView):
    template_name = "users/creators_profile.html"
    context_object_name = "recipes"

    def get_queryset(self):
        return Recipe.objects.filter(author__id=self.kwargs["user_id"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["creator"] = auth.get_user_model().objects.filter(
            pk=context["recipes"][0].author.pk
        )
        return context

book_of_recipes/users/templates/users/creators_profile.html
{% extends 'base.html' %}
{% load static %}
{% load cart_tags %}
{% block content %}
      <!-- Контент на странице -->
      <div class="bg-white p-4 mb-4 rounded custom-shadow row">
        <div class="col-8 p-lg-5">
            <h2 class="text-sm-center text-primary"><strong>Книга рецептов</strong></h2>
            <br>
            {% for recipe in recipes %}
            <div class="card mb-3 border-primary" style="max-width: 540px;">
              <div class="row g-0">
                <div class="col-md-4">
                  {% if recipe.image %}
                  <img src="{{ recipe.image.url }}" class="img-fluid rounded-start" alt="{{ recipe.name_recipe }}"> 
                  {% else %}
                  <img src="{% static 'deps/images/Not found image.png' %}" class="img-fluid rounded-start" alt="{{ recipe.name_recipe }}">
                  {% endif %}
                </div>
                <div class="col-md-8">
                  <div class="card-body">
                    <h5 class="card-title text-danger">{{ recipe.category }}</h5>
                    <a class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" 
                    href="{% url 'recipe_catalog:recipe' recipe.slug %}">
                      <strong><h5 class="card-title">{{ recipe.name_recipe }}</h5></strong></a>
                    <p class="card-text"><strong>Время приготовления:</strong> {{ recipe.cooking_time }} мин</p>
                    <p class="card-text"><small class="text-body-secondary">{{ creator.first_name }} добавил(а) рецепт:</strong> {{ recipe.date_of_creation }} </small></p>
                  </div>
                </div>
              </div>
            </div>
              {% endfor %}
          </div>
        <div class="col-4 m-5" style="width: 200px;">
          
          {% for creator in creator  %}
          
            {% if creator.image  %}
                <img src="{{ creator.image.url }}"
                    alt="Аватар пользователя" class="img-fluid rounded-circle rounded mx-auto d-block" 
                    style="max-width: 150px;">
                {% else %}
                <img src="{% static 'deps/images/baseavatar.jpg' %}"
                alt="Аватар пользователя" class="img-fluid rounded-circle rounded mx-auto d-block"
                style="max-width: 150px;">
                {% endif %}
                <h3 class=" text-primary text-center">{{ creator }}</h3>
          
                  <div class="text-center">
                    
                      <ul class="list-group">
                     <li class="list-group-item d-flex justify-content-between align-items-center">
                        {% quantity_subscribers creator.id as subscribers %}
                        Подписчики
                        <a href="{% url 'cart:subscribers' creator.id %}">
                          <span class="badge text-bg-primary rounded-pill">{{ subscribers }}</span>
                        </a>
                      </li>
                      <li class="list-group-item d-flex justify-content-between align-items-center">
                        {% quantity_favorite_authors  creator.id as quantity %} 
                        Подписки
                        <a href="{% url 'cart:favorite_authors' creator.id %}">
                          <span class="badge text-bg-primary rounded-pill">{{ quantity }}</span>
                        </a>
                      </li> 
                      <li class="list-group-item d-flex justify-content-between align-items-center">
                        Рецепты
                        {%  user_recipe  creator.id as quantity_recipes %}
                        <span class="badge text-bg-primary rounded-pill">{{ quantity_recipes.count }}</span>
                      </li>
                    </ul>
                    {% if user.is_authenticated %}
                    <div class="list-group">
                      {% checking_for_a_subscription request creator.id as check %} 
                      {% if check == 1 %}
                        <a href="{% url 'cart:create_subscription' creator.id %}" class="list-group-item list-group-item-action list-group-item-info" title="Отменить подписку"> вы подписанны </a>
                        {% elif check == 2 %}
                        <a href="{% url 'cart:create_subscription' creator.id %}" class="list-group-item list-group-item-action list-group-item-info">
                          Подписаться в ответ
                        </a>
                        {% else %}
                        <a href="{% url 'cart:create_subscription' creator.id %}" class="list-group-item list-group-item-action list-group-item-info">
                          Подписаться
                        </a>
                      {% endif %}

                      {% endif %}
                    </div>
                    </div>
                  </div> 
                  {% endfor %}
          </div>
      
          </div>
      </div>           
{% endblock %}

book_of_recipes/users/templates/users/password_change_done.html
{% extends 'base.html' %}
 
{% block content %}
<h1>Пароль успешно изменен!</h1>
 
<p >Вы успешно изменили пароль. <a href="{% url 'user:profile_user' %}">Вернуться в профиль.</a></p>
{% endblock %}

book_of_recipes/users/templates/users/password_change_form.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}
<div class="row">
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
        <h2 class="text-center mb-4">Изменение пароля</h2>
        <form  method="post">
          {% csrf_token %}
          <div class="form-error">{{ form.non_field_errors }}</div>
          <div class="row">
            <div class="col-md-6 mb-3">
              <label for="id_old_password" class="form-label">Старый пароль*</label>
              <input
                type="password"
                class="form-control"
                id="id_old_password"
                value="{% if form.old_password.value %}{{ form.old_password.value }}{% endif %}"
                name="old_password"
                placeholder="Введите старый  пароль"
                required/>
              {% if form.old_password.errors %}
              <div class="alert alert-danger alert-dismissible fade show">
                {{ form.old_password.errors }}
              </div>
              {% endif %}
            </div>
            <div class="col-md-6 mb-3">
                <label for="id_new_password1" class="form-label">Новый пароль*</label>
                <input
                  type="password"
                  class="form-control"
                  id="id_new_password1"
                  value="{% if form.new_password1.value %}{{ form.new_password1.value }}{% endif %}"
                  name="new_password1"
                  placeholder="Введите новый пароль"
                  required/>
                {% if form.new_password1.errors %}
                <div class="alert alert-danger alert-dismissible fade show">
                  {{ form.new_password1.errors }}
                </div>
                {% endif %}
              </div>

            <div class="col-md-6 mb-3">
              <label for="id_password2" class="form-label"
                >Подтверждение пароля*</label>
              <input
                type="password"
                class="form-control"
                id="id_new_password2"
                value="{% if form.new_password1.value %}{{ form.new_password1.value }}{% endif %}"
                name="new_password2"
                placeholder="Подтвердите пароль"
                required/>
              {% if form.new_password2.errors %}
              <div class="alert alert-danger alert-dismissible fade show">
                {{ form.new_password2.errors }}
              </div>
              {% endif %}
            </div>
          </div>
          <button type="submit" class="btn btn-dark btn-block">
            Изменить пароль
          </button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

book_of_recipes/users/templates/users/registration.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}
<div class="row">
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
        <h2 class="text-center mb-4">Регистрация</h2>
        <form action="{% url 'user:registration' %}" method="post">
          {% csrf_token %}
          <div class="row">
            <div class="col-md-6 mb-3">
              <label for="id_first_name" class="form-label">Имя*</label>
              <input
                type="text"
                class="form-control"
                id="id_first_name"
                name="first_name"
                value="{% if form.first_name.value %}
                        {{ form.first_name.value }}
                        {% endif %}"
                placeholder="Введите ваше имя"
                required
              />
              {% if form.first_name.errors %}
              <div class="alert alert-danger alert-dismissible fade show">
                {{ form.first_name.errors }}
              </div>
              {% endif %}
            </div>
            <div class="col-md-6 mb-3">
              <label for="id_last_name" class="form-label">Фамилия*</label>
              <input
                type="text"
                class="form-control"
                id="id_last_name"
                value="{% if form.last_name.value %}
                {{ form.last_name.value }}
                {% endif %}"
                name="last_name"
                placeholder="Введите вашу фамилию"
                required
              />
              {% if form.last_name.errors %}
              <div class="alert alert-danger alert-dismissible fade show">
                {{ form.last_name.errors }}
              </div>
              {% endif %}
            </div>
            <div class="col-md-6 mb-3">
              <label for="id_username" class="form-label"
                >Имя пользователя*</label
              >
              <input
                type="text"
                class="form-control"
                id="id_username"
                value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                name="username"
                placeholder="Введите ваше имя пользователя"
                required
              />
              {% if form.username.errors %}
              <div class="alert alert-danger alert-dismissible fade show">
                {{ form.username.errors }}
              </div>
              {% endif %}
            </div>
            <div class="col-md-6 mb-3">
              <label for="id_email" class="form-label">Email*</label>
              <input
                type="email"
                class="form-control"
                id="id_email"
                value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                name="email"
                placeholder="Введите ваш email"
                required
              />
              {% if form.email.errors %}
              <div class="alert alert-danger alert-dismissible fade show">
                {{ form.email.errors }}
              </div>
              {% endif %}
            </div>
            <div class="col-md-6 mb-3">
              <label for="id_password1" class="form-label">Пароль*</label>
              <input
                type="password"
                class="form-control"
                id="id_password1"
                value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
                name="password1"
                placeholder="Введите пароль"
                required
              />
              {% if form.password1.errors %}
              <div class="alert alert-danger alert-dismissible fade show">
                {{ form.password1.errors }}
              </div>
              {% endif %}
            </div>
            <div class="col-md-6 mb-3">
              <label for="id_password2" class="form-label"
                >Подтверждение пароля*</label
              >
              <input
                type="password"
                class="form-control"
                id="id_password2"
                value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
                name="password2"
                placeholder="Подтвердите пароль"
                required
              />
              {% if form.password2.errors %}
              <div class="alert alert-danger alert-dismissible fade show">
                {{ form.password2.errors }}
              </div>
              {% endif %}
            </div>
          </div>
          <button type="submit" class="btn btn-dark btn-block">
            Зарегистрироваться
          </button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

book_of_recipes/users/templates/users/user_profile.html
{% extends 'base.html' %}
{% load static %}
{% load cart_tags %}
{% block content %}
      <!-- Контент на странице -->
      <div class="bg-white mt-3 p-4 mb-4 rounded custom-shadow row">
        <div class="col-8 p-lg-5">
            <h2 class="text-sm-center text-primary"><strong>Книга рецептов</strong></h2>
            <br>
            {% for recipe in recipes %}
            <div class="card mb-3 border-primary" style="max-width: 540px;">
              <div class="row g-0">
                <div class="col-md-4">
                  {% if recipe.image %}
                  <img src="{{ recipe.image.url }}" class="img-fluid rounded-start" alt="{{ recipe.name_recipe }}"> 
                  {% else %}
                  <img src="{% static 'deps/images/Not found image.png' %}" class="img-fluid rounded-start" alt="{{ recipe.name_recipe }}">
                  {% endif %}
                </div>
                <div class="col-md-8">
                  <div class="card-body">
                    <h5 class="card-title text-danger">{{ recipe.category }}</h5>
                    <a class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" 
                    href="{% url 'recipe_catalog:recipe' recipe.slug %}">
                      <strong><h5 class="card-title">{{ recipe.name_recipe }}</h5></strong></a>
                    <p class="card-text"><strong>Время приготовления:</strong> {{ recipe.cooking_time }} мин</p>
                    <p class="card-text"><small class="text-body-secondary">{{ user.first_name }} добавил(а) рецепт:</strong> {{ recipe.date_of_creation }} </small></p>
                  </div>
                </div>
              </div>
            </div>
              {% endfor %}
          </div>
        <div class="col-4 m-5" style="width: 200px;">
            {% if user.image  %}
                <img src="{{ user.image.url }}"
                    alt="Аватар пользователя" class="img-fluid rounded-circle rounded mx-auto d-block" 
                    style="max-width: 150px;">
                {% else %}
                <img src="{% static 'deps/images/baseavatar.jpg' %}"
                alt="Аватар пользователя" class="img-fluid rounded-circle rounded mx-auto d-block"
                style="max-width: 150px;">
                {% endif %}
                <h3 class=" text-primary text-center">{{ user }}</h3>
                  <div class="text-center">
                    <ul class="list-group">
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                      {% quantity_subscribers user.id as subscribers %}
                      Подписчики
                      <a href="{% url 'cart:subscribers' user.id %}">
                        <span class="badge text-bg-primary rounded-pill">{{ subscribers }}</span>
                      </a>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                      {% quantity_favorite_authors  user.id as quantity %} 
                      Подписки
                      <a href="{% url 'cart:favorite_authors' user.id %}">
                        <span class="badge text-bg-primary rounded-pill">{{ quantity }}</span>
                      </a>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                      {% favorites_recipes request as  quantity_favrecipes %}
                      Избранное
                      <a href="{% url 'cart:favorite_recipes' %}"><span class="badge text-bg-primary rounded-pill">{{ quantity_favrecipes.count }}</span></a>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                      {%  user_recipe  user.id as quantity_recipes %}
                      Рецепты
                      <span class="badge text-bg-primary rounded-pill">{{ quantity_recipes.count }}</span>
                    </li>
                  </ul>
                  <div class="list-group">
                    <a href="{% url 'user:user_settings' %}" class="list-group-item list-group-item-action list-group-item-info">
                      Изменить данные
                    </a>
                  </div>
                  </div>
          </div>
      
          </div>
      </div>           
{% endblock %}

book_of_recipes/users/templates/users/user_settings.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
      <!-- Контент на странице -->
      <div class="row">
        <div class="container mt-5">
            <div class="row">
                <!-- Профиль с данными пользователя -->
                <div class="col-md-5">
                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="text-center mb-4">Профиль пользователя</h3>
                        <form action="{% url 'user:user_settings' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12 mb-3 text-center">
                                    {% if user.image  %}
                                    <img src="{{ user.image.url }}"
                                        alt="Аватар пользователя" class="img-fluid rounded-circle"
                                        style="max-width: 150px;">
                                    {% else %}
                                    <img src="{% static 'deps/images/baseavatar.jpg' %}"
                                    alt="Аватар пользователя" class="img-fluid rounded-circle"
                                    style="max-width: 150px;">
                                    {% endif %}
                                    <input type="file" class="form-control mt-3" id="id_image" name="image"
                                        accept="image/*">
                                        {% if form.image.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.image.errors }}</div>
                                        {% endif %}
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_first_name" class="form-label">Имя*</label>
                                    <input type="text" class="form-control" id="id_first_name" name="first_name"
                                        placeholder="Введите ваше имя" value="{{ form.first_name.value }}" required>
                                        {% if form.first_name.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                        {% endif %}
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_last_name" class="form-label">Фамилия*</label>
                                    <input type="text" class="form-control" id="id_last_name" name="last_name"
                                        placeholder="Введите вашу фамилию" value="{{ form.last_name.value }}" required>
                                        {% if form.last_name.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                        {% endif %}
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_username" class="form-label">Имя пользователя*</label>
                                    <input type="text" class="form-control" id="id_username" name="username"
                                        placeholder="Введите ваше имя пользователя" value="{{ form.username.value }}" required>
                                        {% if form.username.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                        {% endif %}
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_email" class="form-label">Email*</label>
                                    <input type="email" class="form-control" id="id_email" name="email"
                                        placeholder="Введите ваш email *youremail@example.com" value="{{ form.email.value }}"
                                        required>
                                        {% if form.email.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                        {% endif %}
                                </div>
                            </div>
                            <button type="submit" class="btn btn-dark">Сохранить</button>
                        </form>
                        <hr>
                        <p><a href="{% url 'user:password_change' %}">Сменить пароль</a></p>
                        
                    </div>
                </div>
               
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}