book_of_recipes/book_of_recipes/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('catalog.urls', namespace='recipe_catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')) ,
]


if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
        ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book_of_recipes/carts/urls.py
from django.urls import path
from carts import views


app_name = "carts"

urlpatterns = [
    path("favorite-recipes/", views.ShowFavoriteRecipes.as_view(), name="favorite_recipes"),
    path("cart-add/<int:recipe_id>/", views.cart_add, name="cart_add"),
    path("users-recipes/", views.UsersRecipesPage.as_view(), name="users_recipes"),
    path(
        "create-subscription/<int:creator_id>/",
        views.create_subscription,
        name="create_subscription",
    ),
    path(
        "favorite-authors/<int:user_id>/",
        views.favorite_authors,
        name="favorite_authors",
    ),
    path(
        "subscribers/<int:user_id>/", views.subscribers_of_the_user, name="subscribers"
    ),
]

book_of_recipes/catalog/urls.py
from django.urls import  path
from catalog import views

app_name = "catalog"

urlpatterns = [
    path('search/',views.show_catalog, name='search' ),
    path("category/<slug:category_slug>/", views.show_catalog, name="catalog"),
    path("recipe/<slug:recipe_slug>/", views.ShowRecipe.as_view(), name="recipe"),
    path("user-add-recipe/", views.AddPage.as_view(), name="user_add_recipe"),
    path(
        "change/<slug:slug>/", views.UpdatePage.as_view(), name="change_the_recipe"
    ),
    path("remove/<slug:slug>/", views.DeletePage.as_view(), name="remove"),
    ]

book_of_recipes/main/urls.py
from django.urls import path
from main import views


app_name = "main"

urlpatterns = [
  path('', views.MainPage.as_view(), name='index'),
  path('about/', views.AboutPage.as_view(), name='about'),
  
 
]

book_of_recipes/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView
from django.urls import path
from users import views


app_name = "users"

urlpatterns = [
    path("login/", views.LoginUser.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "password-change/", views.UserPasswordChange.as_view(), name="password_change"
    ),
    path(
        "password-change/done/",
        PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
        name="password_change_done",
    ),
    path("registration/", views.RegistrationUser.as_view(), name="registration"),
    path("user-settings/", views.user_settings, name="user_settings"),
    path("profile/", views.ShowProfile.as_view(), name="profile_user"),
    
    path("creators/", views.ShowAuthors.as_view(), name="creators"),
    path("creator/<int:user_id>/", views.ShowAuthorProfile.as_view(), name="creator"),
]

book_of_recipes/catalog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify


class Category(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name="Название")
    slug = models.SlugField(
        max_length=200, unique=True, blank=True, null=True, verbose_name="URL"
    )

    class Meta:
        db_table = "category"
        verbose_name = "Категорию"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name


def translit_to_eng(s: str):
    d = {
        "а": "a",
        "б": "b",
        "в": "v",
        "г": "g",
        "д": "d",
        "е": "e",
        "ё": "yo",
        "ж": "zh",
        "з": "z",
        "и": "i",
        "к": "k",
        "л": "l",
        "м": "m",
        "н": "n",
        "о": "o",
        "п": "p",
        "р": "r",
        "с": "s",
        "т": "t",
        "у": "u",
        "ф": "f",
        "х": "h",
        "ц": "c",
        "ч": "ch",
        "ш": "sh",
        "щ": "shch",
        "ь": "",
        "ы": "y",
        "ъ": "",
        "э": "r",
        "ю": "yu",
        "я": "ya",
    }
    return "".join(map(lambda x: d[x] if d.get(x, False) else x, s.lower()))


class Recipe(models.Model):
    name_recipe = models.CharField(
        max_length=200, unique=True, verbose_name="Название рецепта"
    )
    slug = models.SlugField(
        max_length=300, unique=True, verbose_name="URL", blank=True, null=True
    )
    description = models.TextField(verbose_name="Описание", blank=True, 
                                   null=True)
    ingredients = models.CharField(
        max_length=300, blank=True, null=True, verbose_name="ингредиенты"
    )
    cooking_steps = models.TextField(verbose_name="Шаги приготовления")
    cooking_time = models.IntegerField(verbose_name="Время приготовления")
    image = models.ImageField(upload_to="recipe_image", blank=True, null=True)
    category = models.ForeignKey(
        to=Category, on_delete=models.CASCADE, verbose_name="Категория", related_name="category"
    )
    date_of_creation = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата добавления рецепта"
    )
    author = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, verbose_name="Автор", 
        related_name="authors"
    )
    class Meta:
        db_table = "recipe"
        verbose_name = "Рецепт"
        verbose_name_plural = "Рецепты"

    def __str__(self):
        return self.name_recipe

    def save(self, *args, **kwargs):
        self.slug = slugify(translit_to_eng(self.name_recipe))
        super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse("recipe_catalog:recipe", kwargs={"recipe_slug": self.slug})

book_of_recipes/catalog/forms.py
from django import forms
from catalog.models import Recipe


class UserRecipeForm(forms.ModelForm):

    class Meta:
        model = Recipe
        fields = [
            'name_recipe',
            'slug',
            'description',
            'ingredients',
            'cooking_steps',
            'cooking_time',
            'image', 
            'category','author' ]
    image = forms.ImageField(required=False)

book_of_recipes/catalog/views.py
from django.shortcuts import redirect, render
from django.core.paginator import Paginator
from django.shortcuts import get_list_or_404, get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    UpdateView,
)
from catalog.models import Recipe

from .forms import UserRecipeForm


class ShowRecipe(DetailView):
    model = Recipe
    template_name = "catalog/recipe.html"
    slug_url_kwarg = "recipe_slug"
    context_object_name = "recipe"


class AddPage(CreateView):
    form_class = UserRecipeForm
    template_name = "catalog/user_add_recipe.html"


class UpdatePage(UpdateView):
    model = Recipe
    fields = [
        "name_recipe",
        "description",
        "ingredients",
        "cooking_steps",
        "cooking_time",
        "image",
        "category",
    ]
    template_name = "catalog/change_the_recipe.html"


class DeletePage(DeleteView):
    model = Recipe
    success_url = reverse_lazy("main:index")
    context_object_name = "recipe"


def show_catalog(request, category_slug=None):
    page = request.GET.get("page", 1)
    on_image = request.GET.get("on_image", None)
    order_by = request.GET.get("order_by", None)

    if category_slug == "all":
        recipes = Recipe.objects.all()
        if on_image:
            recipes = Recipe.objects.exclude(image="")
        if order_by and order_by != "default":
            recipes = Recipe.objects.order_by(order_by)
        if on_image and order_by and order_by != "default":
            recipes = Recipe.objects.order_by(order_by).exclude(image="")

    else:
        recipes = get_list_or_404(Recipe, category__slug=category_slug)

        if on_image:
            recipes = Recipe.objects.filter(category__slug=category_slug).exclude(
                image=""
            )
        if order_by and order_by != "default":
            recipes = Recipe.objects.filter(category__slug=category_slug).order_by(
                order_by
            )
        if on_image and order_by and order_by != "default":
            recipes = (
                Recipe.objects.filter(category__slug=category_slug)
                .order_by(order_by).exclude(image="")
            )
       
    paginator = Paginator(recipes, 6)
    current_page = paginator.page(int(page))
    slug_url = category_slug
    context = {
        "title": "Cooking at home - все рецепты ",
        "recipes": current_page,
        "slug_url": slug_url,
    }
    return render(request, "catalog/catalog.html", context)

book_of_recipes/catalog/templates/catalog/change_the_recipe.html
{% extends 'base.html' %} {% load static %} 
{% load recipe_tags %}
{% block content %}
<div class="row">
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
        <h2 class="text-center mb-4">Редактирование рецепта</h2>
        <form action="{% url 'catalog:change_the_recipe' recipe.slug %}" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="row">
           <div class="col-md-6 mb-3">
            <strong><h5 class="card-title">{{ recipe.name_recipe }}</h5></strong>
              <input
                type="text"
                class="form-control"
                id="id_name_recipe"
                name="name_recipe"
                value="{% if form.name_recipe.value %}{{ form.name_recipe.value }}{% endif %}"
                placeholder="Введите название рецепта"required>
              {% if form.name_recipe.errors %}
              <div class="alert alert-danger alert-dismissible fade show">
                {{ form.name_recipe.errors }}
              </div>
              {% endif %}
            </div>
            <div class="col-md-6 mb-3">
            <input
            type="hidden"
            class="form-control"
            id="id_slug"
            name="slug"
            value="{{form.slug.value}}"
            required>
          </div>
            <div class="col-md-6 mb-3">
              <label for="id_description" class="form-label">Описание*</label>
              <input
                type="text"
                class="form-control"
                id="id_dedescription"
                value="{% if form.description.value %}{{ form.description.value }}{% endif %}"
                name="description"
                placeholder="Введите описание"
                required>
                {% if form.description.errors %}
                <div class="alert alert-danger alert-dismissible fade show">
                  {{ form.description.errors }}
                </div>
                {% endif %}
            </div>
            <div class="col-md-6 mb-3">
              <label for="id_ingredients" class="form-label">Ингредиенты*</label>
              <input
                type="text"
                class="form-control"
                id="id_ingredients"
                value="{% if form.ingredients.value %}{{ form.ingredients.value }}{% endif %}"
                name="ingredients"
                placeholder="Введите необходимые ингредиенты" required>
                {% if form.ingredients.errors %}<div class="alert alert-danger alert-dismissible fade show">{{ form.ingredients.errors }}</div>
                {% endif %}
            </div>
            <div class="col-md-6 mb-3">
              <label for="id_cooking_steps" class="form-label">Шаги приготовления*</label>
              <textarea cols="30" rows="20"
                class="form-control"
                id="id_cooking_steps"
                name="cooking_steps"
                placeholder="Введите шаги приготовления" required>{% if form.cooking_steps.value %}{{ form.cooking_steps.value }}{% endif %}</textarea>
                {% if form.cooking_steps.errors %}<div class="alert alert-danger alert-dismissible fade show">{{ form.cooking_steps.errors }}</div>
                {% endif %}
            </div>
            <div class="col-md-6 mb-3">
              <label for="id_cooking_time" class="form-label">Время приготовления*</label>
              <input
                class="form-control"
                type="number"
                id="id_cooking_time"
                value="{% if form.cooking_time.value %}{{ form.cooking_time.value }}{% endif %}"
                name="cooking_time"
                placeholder="Введите время приготовления в мин" required>
                {% if form.cooking_time.errors %}
                <div class="alert alert-danger alert-dismissible fade show">
                  {{ form.cooking_time.errors }}
                </div>
                {% endif %}
            </div>
            <div class="col-md-6 mb-3">
                {% if recipe.image %}
                <img src="{{ recipe.image.url }}" class="img-fluid" alt="{{ recipe.name_recipe }}">
                {% else %}
                <img src="{% static 'deps/images/Not found image.png' %}" class="img-fluid" alt="{{ recipe.name_recipe }}">
                {% endif %}   
                    <input type="file" class="form-control mt-3" id="id_image" name="image"
                        accept="image/*" height="663">
                        {% if form.image.errors %}
                        <div class="alert alert-danger alert-dismissible fade show">{{ form.image.errors }}</div>
                        {% endif %}
                </div>
            <div class="col-md-6 mb-3">
                <label for="id_category" class="form-label">Категория*:</label>
                {% tag_category as categories %}
                <select
                id="id_category"
                name="category"
                required>
                <option value="">--Выберите категорию--</option>
                {% for cat in categories  %}
                <option  value="{{ cat.id }}">{{ cat.name }}</option>
                {% endfor %}
            </select>
            {% if form.cat.errors %}
            <div class="alert alert-danger alert-dismissible fade show">{{ form.cat.errors }}</div>
            {% endif %}
            </div>
            <div class="col-md-6 mb-3">
              <input
                class="form-control"
                type="hidden"
                id="id_author"
                value="{{ user.id }}"
                name="author"
                required>
                </div>     
          </div>
          <button type="submit" class="btn btn-dark btn-block btn-sm">Редактировать рецепт</button>
        </form>
        <br>
        <a href="{% url 'main:index' %}"><button type="button" class="btn btn-secondary btn-sm">Отменить редактирование рецепта</button></a>
    </div>
    </div>
  </div>
</div>
{% endblock content %}

book_of_recipes/catalog/templates/catalog/recipe.html
{% extends 'base.html' %}
{% load static %}
{% load cart_tags %}
{% block content %}
<div class="container mt-5">
    <div class="card mb-4 custom-shadow">
        <div class="row">
            <!-- Миниатюры -->
            <div class="col-md-4">
                {% if recipe.image %}
                <img src="{{ recipe.image.url }}" height="663" class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1" 
                alt="{{ recipe.name_recipe }}">
                {% else %}
                <img src="{% static 'deps/images/Not found image.png' %}" height="663" class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1" alt="{{ recipe.name_recipe }}">
                {% endif %}
            </div>
            <div class="modal fade" id="imageModal1" tabindex="-1"
                aria-labelledby="imageModal1Label" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="imageModal1Label">{{ recipe.name_recipe|truncatewords:4 }}</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                aria-label="Закрыть"></button>
                        </div>
                        <div class="modal-body">
                            {% if recipe.image %}
                            <img src="{{ recipe.image.url }}" class="img-fluid" alt="{{ recipe.name_recipe }}">
                            {% else %}
                            <img src="{% static 'deps/images/Not found image.png' %}" class="img-fluid" alt="{{ recipe.name_recipe }}">
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
       
        <!-- Описание товара -->
        <div class="card-body">
            <strong><h5 class="card-title">{{ recipe.name_recipe }}</h5></strong>
            <p class="card-text">{{ recipe.description }}</p>
            <p class="card-text"><strong>Ингредиенты:</strong> {{ recipe.ingredients }}</p>
            <p class="card-text"><strong>Рецепт</strong> {{ recipe.cooking_steps }}</p>
            <p class="card-text"><strong>Время приготовления:</strong> {{ recipe.cooking_time }} мин</p>
            <div>
                <p class="card-text"><a 
                    class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover"
                    href="{% if user.id == recipe.author.id %}{% url 'user:profile_user' %}{% else %}
                    {% url 'user:creator' recipe.author.id %}{% endif %}">
                    Автор: {{ recipe.author}}</=></p> 
                <p class="card-text">
                    {% if recipe.author == user %}<a href="{% url 'recipe_catalog:change_the_recipe' recipe.slug %}">
                    <button class="btn btn-primary">Редактировать рецепт</button></a>
                    <a href="{% url 'recipe_catalog:remove' recipe.slug %}">
                    <button class="btn btn-primary">Удалить рецепт</button></a>
                </p>{% endif %}
                </div>        
        </div>
     {% if user.is_authenticated %}
            <div class="col-md-4 " id="favorites-selection" >
                {% if user.is_authenticated %}
                <p class="mt-3">
                    {% total_number_of_favorites recipe.slug as favorites %}
                    {% checking_for_a_favorites request recipe.id as like %}
                    {% if like %}
                    <a href="{% url 'cart:cart_add' recipe.id %}"><button class="btn ">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bookmark-plus-fill" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M2 15.5V2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.74.439L8 13.069l-5.26 2.87A.5.5 0 0 1 2 15.5m6.5-11a.5.5 0 0 0-1 0V6H6a.5.5 0 0 0 0 1h1.5v1.5a.5.5 0 0 0 1 0V7H10a.5.5 0 0 0 0-1H8.5z"/>
                          </svg>
                    </button></a>
                    {% else %}
                    <a href="{% url 'cart:cart_add' recipe.id %}"><button  class="btn ">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bookmark-plus" viewBox="0 0 16 16">
                            <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1z"/>
                            <path d="M8 4a.5.5 0 0 1 .5.5V6H10a.5.5 0 0 1 0 1H8.5v1.5a.5.5 0 0 1-1 0V7H6a.5.5 0 0 1 0-1h1.5V4.5A.5.5 0 0 1 8 4"/>
                          </svg>
                          
                    </button></a>
                    {% endif %}
                    <span class=" text-secondary" id="goods-in-cart-count">{{ favorites.total_number }}</span> </a>
                </p>
                    {% endif %}
                    {% endif %}
</div>
{% endblock %} 

book_of_recipes/catalog/templates/catalog/recipe_confirm_delete.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="row">
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
        <form method="POST">
          {% csrf_token %}
          <p>Вы уверенны что хотите удалить "{{ recipe }}"?</p>
          {{ form }}
          <input type="submit" value="Удалить" />
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

book_of_recipes/catalog/templates/catalog/user_add_recipe.html
{% extends 'base.html' %} {% load static %} 
{% load recipe_tags %}
{% block content %}
<div class="row">
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
        <h2 class="text-center mb-4">Добавление рецепта</h2>
        <form action="{% url 'recipe_catalog:user_add_recipe' %}" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="row">
           <div class="col-md-6 mb-3">
              <label for="id_name_recipe" class="form-label">Название рецепта*</label>
              <input
                type="text"
                class="form-control"
                id="id_name_recipe"
                name="name_recipe"
                value="{% if form.name_recipe.value %}{{ form.name_recipe.value }}{% endif %}"
                placeholder="Введите название рецепта"required>
              {% if form.name_recipe.errors %}
              <div class="alert alert-danger alert-dismissible fade show">
                {{ form.name_recipe.errors }}
              </div>
              {% endif %}
            </div>
            <div class="col-md-6 mb-3">
            <input
            type="hidden"
            class="form-control"
            id="id_slug"
            name="slug"
            value="{{form.slug.value}}"
            required>
          </div>
            <div class="col-md-6 mb-3">
              <label for="id_description" class="form-label">Описание*</label>
              <input
                type="text"
                class="form-control"
                id="id_dedescription"
                value="{% if form.description.value %}{{ form.description.value }}{% endif %}"
                name="description"
                placeholder="Введите описание"
                required>
                {% if form.description.errors %}
                <div class="alert alert-danger alert-dismissible fade show">
                  {{ form.description.errors }}
                </div>
                {% endif %}
            </div>
            <div class="col-md-6 mb-3">
              <label for="id_ingredients" class="form-label">Ингредиенты*</label>
              <input
                type="text"
                class="form-control"
                id="id_ingredients"
                value="{% if form.ingredients.value %}{{ form.ingredients.value }}{% endif %}"
                name="ingredients"
                placeholder="Введите необходимые ингредиенты" required>
                {% if form.ingredients.errors %}<div class="alert alert-danger alert-dismissible fade show">{{ form.ingredients.errors }}</div>
                {% endif %}
            </div>
            <div class="col-md-6 mb-3">
              <label for="id_cooking_steps" class="form-label">Шаги приготовления*</label>
              <textarea cols="30" rows="20"
                class="form-control"
                id="id_cooking_steps"
                value="{% if form.cooking_steps.value %}{{ form.cooking_steps.value }}{% endif %}"
                name="cooking_steps"
                placeholder="Введите шаги приготовления" required></textarea>
                {% if form.cooking_steps.errors %}<div class="alert alert-danger alert-dismissible fade show">{{ form.cooking_steps.errors }}</div>
                {% endif %}
            </div>
            <div class="col-md-6 mb-3">
              <label for="id_cooking_time" class="form-label">Время приготовления*</label>
              <input
                class="form-control"
                type="number"
                id="id_cooking_time"
                value="{% if form.cooking_time.value %}{{ form.cooking_time.value }}{% endif %}"
                name="cooking_time"
                placeholder="Введите время приготовления в мин" required>
                {% if form.cooking_time.errors %}
                <div class="alert alert-danger alert-dismissible fade show">
                  {{ form.cooking_time.errors }}
                </div>
                {% endif %}
            </div>
            <div class="col-md-6 mb-3">
                <label for="id_image" class="form-label">Фотография*</label>
                    <input type="file" class="form-control mt-3" id="id_image" name="image"
                        accept="image/*" height="663">
                        {% if form.image.errors %}
                        <div class="alert alert-danger alert-dismissible fade show">{{ form.image.errors }}</div>
                        {% endif %}
                </div>
            <div class="col-md-6 mb-3">
                <label for="id_category" class="form-label">Категория*:</label>
                {% tag_category as categories %}
                <select
                id="id_category"
                name="category"
                required>
                <option value="">--Выберите категорию--</option>
                {% for cat in categories  %}
                <option  value="{{ cat.id }}">{{ cat.name }}</option>
                {% endfor %}
            </select>
            {% if form.cat.errors %}
            <div class="alert alert-danger alert-dismissible fade show">{{ form.cat.errors }}</div>
            {% endif %}
            </div>
            <div class="col-md-6 mb-3">
              <input
                class="form-control"
                type="hidden"
                id="id_author"
                value="{{ user.id }}"
                name="author"
                required>
                </div> 
                
          </div> 
          <button type="submit" class="btn btn-dark btn-block">
            Добавить рецепт
          </button>
        </form>
    </div>
    </div>
  </div>
</div>
{% endblock content %}